OpenVE/comunidades-en-telegram

- README.md
añadiendo grupo de administradores linux de Venezuela
> añadiendo grupo de administradores linux de Venezuela

- README.md
Grupo creado ayer y que pasa a formar parte de las comunidades en telegram
> Agregado el grupo de LibreOffice, administrado por @Tur3c0

- README.md
como tenia cierto tiempo libre y estaba ocioso, me puse a revisar el ordenamiento alfabetico de los grupos, mejorar la lectura del md, y reescribir la licencia en formato MD, bueno eso es todo por hoy, chao...
> Algunos cambios

- README.md
Modifiqué los enlaces públicos para los grupos de **HTML/CSS Venezuela; PHP Venezuela y LibreOffice Venezuela** en los que soy administrador. Agregué, además, en username del administrador del grupo de **Git (@johannn)**.
> Actualización de enlaces y nombre de Administrador

- README.md
El siguiente código agregra el grupo de Yii a la lista.
> Añadiendo el enlace del grupo de Yii

- README.md
Fue agregado los username de los administradores del grupo Angular
> Se agrega lista de administradores del grupo de Angular

- README.md
New group created to talk about hybrid mobile apps.
> :star: Add hybrid mobile development to the list

- README.md
The vim group was converted to super group 💪
> Add Vim group link

- README.md
Agrego el nuevo enlace al grupo de Wikimedia Venezuela.
> Modificando el enlace para el grupo de Wikimedia Venezuela.

- README.md
Grupo para desarrollo de videojuegos de Venezuela.
> Add Desarrollo de VideoJuegos Venezuela

- README.md
- Actualizacion de informacion
- Mejoras en formato
> Actualizacion de informacion y mejoras en formato

- README.md
Freelancers Community Venezuela in Telegram
> Add Freelancers Venezuela

- README.md
Se corrigieron los links para IOT (Era Raspberry, Arduino), RadioGNU y
Bases de Datos.
> Corregidos varios links rotos y administradores

- README.md
Corregidos los canales Bitcoin, Libros y Mozilla
El bot de python fue eliminado (Conversado con Willicab)
Algunos cambios fueron tomados del fork de @ajsb85
> Corregidos varios links

- README.md
Se incorpora la Comunidad de SIGESP
> Se incluye la Comunidad de Usuarios y Administradores de SIGESP

- README.md
Hola, en este PR solo se realizó la actualización del link que me fue indicado estaba inactivo.
Saludos
> Actualización del link de Desarrollo de Video Juegos

- README.md
Agregando nueva comunidad para emprendedores en tecnología para la zona oriental del país.
> Agregando comunidad IT Oriente 

- README.md
Agregado el grupo de FreeCodeCamp Caracas!.
> Add FCC Caracas

- README.md
Este grupo de Telegram es una comunidad colaborativa que fomenta la comunicación, la asociación y el intercambio de ideas, de análisis o de datos, para garantizar el correcto y rápido desarrollo del software GLPI.
En calidad de aplicación gratuita y de código abierto, se invita a cualquier persona a contribuir al esfuerzo colectivo (con independencia de sus competencias), para lograr más que un individuo trabajando por su propia cuenta: instalando GLPI, probándolo, proponiendo actualizaciones, traducciones … entre otros.
> Add GLPI y Gestión de Servicios de TI

- README.md
Y unos otros detalles arreglados
> Agregado grupo de Reactjs

- README.md
Agregué el grupo de seguridad informática
> Grupo de seguridad informática

- README.md
Siguiendo la intencion de #82, agrego el canal al tope de la lista.
> Agregado link al grupo de openve

- README.md
Sustitución de los enlaces de telegram al nuevo que se utiliza por defecto en la app.
> Sustitucion de enlaces de telegram

- README.md
Comunidad sobre Firebase 
Ùnete [Firebase Venezuela](https://t.me/firebaseVenezuela) 👥
> Comunidad Firebase de Venezuela.

- README.md
Se agregan admins en las comunidades: 
- _**ngVenezuela**_:  `@leonardocabeza`.
- _**FirebaseVe**_: `@jobsamuel`.
> Agrega Admins en FirebaseVe y ngVenezuela

- README.md
[DEL] - Se elimina por inactividad el grupo Wagtail.
[ADD] - Se añade el grupo Kotlin Venezuela.
> Modificaciones relacionadas al grupo Wagtail y se agrega Kotlin Venezuela

- README.md
Canal de Libros de Programación En Español e Inglés.
> Se añade Canal de Libros de Programación

- README.md
Hey @guerrerocarlos or @ghostbar, please.
> Adds AWSLA

- README.md
Agregado dos nuevos grupos a la lista de comunidades en telegram
* Freecodecamp Coro
* Inteligencia Artificial
> Agregando Freecodecamp Coro y Inteligencia Artificial

- README.md
Por favor agregar Hackers and Founders
> Agregar Hackers and Founder Maracay

- README.md
Desarrolladores .ve 🇻🇪 en el Mundo 🌎, es una comunidad pensada para compartir experiencias migratorias de programadores venezolanos alrededor del mundo.
> feat(ReadMe): Agrega Desarrolladores .ve en el mundo

- README.md
Se agrega a @oteroweb como admin en el canal de emprendimiento.
> Administrador canal de emprendimiento.

- README.md
Canal sobre aplicaciones de Linux, herramientas de desarrollo en Python y recursos para aprendizaje en Python.
> Añadido canales sobre Linux y Python

- README.md
Se rehicieron todos los cambios tanto para el grupo Bash/Zsh/CLI como la creación del grupo de jQuery LA.
@aasanchez, @foursixnine ahí les dejo esa.
> Actualización al grupo Bash/Zsh/CLI y nuevo grupo jQuery LA

- README.md
- Arreglada la alineacion de la tabla en markdown.
- Agregado nuevo admin en el ganal de GoLang
- Corregido el orden alfabetico
> Varios cambios y optimizaciones

- README.md
Arte Libre VE Espacio para  compartir el conocimientos en herramientas de diseño gráfico open source
> Agregado de Nueva Comunidad Tecnologica

- README.md
Nueva comunidad para aquellos que gusten del lenguaje de programación Java
> añadido comunidad java Venezuela

- README.md
modificado el Canal CSL_VE, dueño, admins y enlace
> modificado el Canal CSL_VE, dueños, admins y enlace

- README.md
Work In Progress, no hacer merge, pero pueden ver los avances y hacer sugerencias, a todos los commits se les hara un squash para que sean un unico commit al repo, por ahora seran todos separados para que se vean los cambios y progreso
> [WIP] Check links y admins

- README.md
Grupo dedicado a discutir hechos Paranormales / Inexplicables.
> Agregado grupo Paranormales

- README.md
Elimina a `@jobsamuel` como administrador de la comunidad y en su lugar agrega a `@osnoser1`.
> docs(ngVenezuela): Actualizacion de admins

- README.md
Resuelve comentarios hechos en el issue #137 , en donde se propone estandarizar la manera en la que se muestran las comunidades agregadas al listado.
> Seguimiento a propuesta de estandar

- CONTRIBUTING.md
- README.md
> Estandarización en colaboraciones

- README.md
borre 2 espacios en blanco y agregue el grupo de LaTeX Latinoamérica
> LaTeX Latino

- README.md
> Cambio de enlace para ingresar a Docker Venezuela

- README.md
De momento tenemos una poca cantidad de Canales, asi que tiene algo de sentido agruparlos, y tambien agregamos ua seccion mas, para cosas que eventualmente eliminariamos? (Porque ya no existan o porque estan inactivos por completo... como por ejemplo el de parkode
Lo del Bin, puede ser tomado como un RFC :)
> Propuesta para mover Canales y una Papelera

- README.md
Grupo orientado a la programación en Rust.
> Añadido grupo Rust Venezuela.

- README.md
Adicionar Canal de Youtubers Vzla
> Adicionando comunidad youtubers vzla

- README.md
Saludos, tengo un portal de noticias reciente y abrí un canal de Telegram para difundir cuando un boletín informativo ha salido, adicionalmente e agregado el mismo canal a su lista de canales y grupos de Telegram, muchas gracias
> Se agrego elemento a la lista de otros temas

- README.md
* Se trasladan los grupos y canales inactivos y con enlaces expirados a la sección correspondiente.
* Se actualiza la información para el grupo Wikimedia Venezuela
> Actualización de canales activos

- README.md
Se añade enlace al canal Wikimedia. 
Se reordenan alfabeticamente las secciones de canales, temas diversos e inactivos.
> Nuevo canal de noticias de WikimediaVe y reordenamiento alfabético.

- README.md
Llego ese momento del año donde comenzamos a cortar rabo y oreja...
> Actualizacion de canales nuevamente

- README.md
se eliminan canales de noticias no relacionados con temas técnicos, se agrega canal de noticias de microsiervos.
> actualiza lista de canales de noticias

- README.md
Saludos,
Siguiendo los pasos descritos, estoy agregando la nueva [comunidad de Katas](https://t.me/daily_katas).
> Agrega comunidad de Katas

- README.md
Creada comunidad de QA para Venezuela
> Comunidad de QA agregada

- README.md
Aprovechando tambien, merge parcial de pr #169
> Agrega el canal de Alexandria (Libros)

- README.md
Considerado bajo la categoría "otros temas".
> Cambio de categoría "Youtubers Venezuela"

- README.md
Favor de agregar grupo Udemy Venezuela.
Grupo para compartir cursos Free, en Rebaja  y recomendaciones de pagos de Udemy
Administradores: @Richzendy y @ThePhoenixBird
> Agregado Udemy Venezuela

- README.md
Solo edición de título del grupo de "Interaction Design" para incluir también el título en inglés "Interaction Design - Diseño Interactivo"
> Interaction Design, título editado

- README.md
> Added millenials en software libre - Update README.md
